sound/misc/Couplebucks.wav
sound/misc/Awwcrap.wav
sound/misc/Awwman.wav
sound/misc/Haha.wav
sound/misc/Dohoo.wav
sound/misc/Ow.wav
sound/misc/Doomed.wav
sound/misc/Beback.wav
sound/misc/Fuck.wav
sound/misc/Cheese.wav
sound/misc/Shutup.wav
sound/misc/Whykillme.wav
sound/misc/Lol.wav
sound/misc/Gay.wav
sound/misc/Holycow.wav
sound/misc/Bullseye.wav
sound/misc/Sword.wav
sound/misc/Help.wav
sound/misc/Bleeeat.wav
maps/aim_ak-colt.res
maps/default.txt